column refreshid format a10
column mviewid format a15
column ref_type format a9
column ref_mode format a9
column atomic format a7
column refreshjyn format 999999
column tablenm format a30
column mviewnm format a30
column object_name format a30
column object_type format a30
column status format a12
column column_name format a30
column column_position format 999999
column line format 99999
column text format a30
column kaihairuleno format 9999
column kaihaihosikikbn format a15
column syunddkbn format 9999
column dbhojinisu format 9999
column addwhere format a30
column refreshid format a10
column mviewid format a15
column ref_type format a9
column ref_mode format a9
column atomic format a7
column refreshjyn format 999999
column tablenm format a30
column jikkostartymd format a10
column kjnymdsabusyscd format a5
column tableid format a12
column tablenm format a30
column kaihaihosikikbn format a5
column jikkosql format a400
column file_name format a30
column tablespace_name format a30
column table_owner format a30
column table_name format a30
column column_name format a30
column index_name format a30
column index_type format a30
column owner format a30
column constraint_name format a30
column constraint_type format a30
column privilege format a30
column owner format a30
column data_type format a30
column data_length format 9999999
column synonym_name format a30
column mview_name format a30
column table_comments format a30
column event_s  format 9999
column event  format a30
column sid format 9999
column serial format 9999
column spid format 9999
column osuser  format a10
column program  format a10
column result   format a30
column gb format 9999999
column directory_name format a30
column directory_path format a30
column tape_dir_name format a10
column ora_dir_name format a30
column kjnsabusyscd format a5
column kjnymdkbn format a5
column grpid format a15
column segment_name format a30
column tablespacenmprefix format a30
column kirikaekbn format a30
column kirikaetaisyodd format a30
column outputobject format a30
column backupcurrentpos format a30
column backupcurrentpartnm format a15
column tablespace_write_from format a15
column tablespace_write_to format a15
column tablespace_read_to format a15
column tablespacenmprefix format a15
column kirikaeruleno format a2
column backupcurrentpos format a15
column backupcondtype format a2
column condpartitioned format a2
column ymdhh24miss format a30
column subsystem format a60
column ignorekbn format a3
column db_link format a30
column host format a20
column username format a30
column property_name format a30
column property_value format a30
column description format a30
column name format a30
column value format a30
column network_name format a30
column trigger_name format a30
column triggering_event format a30
column statistics_name format a45
column activation_level format a30
column log_owner format a30
column log_table format a30
column master format a30
column pga_max_mb format 99999.9
column service_name format a15
column schemaname format a20
column pkg_alloc_mb format a30
column date_time format a20
column machine format a15
column chain_owner format a15
column chain_name format a15
column step_name format a15
column state format a15
column completed format a15
column duration format a30
column start_date format a20
column end_date format a20
column biko_256 format a80
column bunsanfunctionid format a50
column bunsankbn format a10
column bunsansu format 999
column sequence_owner format a15
column max_value format 999999999999999
column bunsanedasu format 999
column kosinusr format a20
column anchorpartnm format a20
column sakisu format 9
column tablename format a30
column sakisu format 9
column resultcode format a60
column pk_cd_id     format a9
column pk_cd        format a5
column cd_id_nm     format a20
column cd_id_nm_btr format a20
column ry           format a15
column hyoj_jn      format 99
column count        format 99
column user_id      format 9999999
column default_tablespace format a30
column temporary_tablespace format a30
column profile format a15
column initial_rsrc_consumer_group format a25
column instance_number format 99    
column instance_name   format a20   
column host_name      format  a20   
column version        format  a20   
column status         format  a15   
column parallel       format  a4    
column thread#        format  99    
column archiver        format a10   
column log_switch_wait  format  a20 
column logins            format a15 
column shutdown_pending  format a20 
column database_status   format a10 
column instance_role     format a10 
column active_state     format  a10 
column blocked           format a10 
set linesize 1000
set pages 10000
set trimspool on
set sqlprompt "_date _user'@'_connect_identifier'>'"
set serverout on size 1000000
set termout on
set echo on
set time on
set timing on